const assert=require("assert");
const http=require("http");
const {spawn}=require("child_process");
const fs=require("fs");
const {io}=require("socket.io-client");
const path=require("path");
const vm=require("vm");
const engine=require("../server");
const port=3299;
const server=spawn(process.execPath,["server.js"],{cwd:path.join(__dirname,".."),env:{...process.env,PORT:String(port)},stdio:["ignore","pipe","inherit"]});
const wait=(ms)=>new Promise((resolve)=>setTimeout(resolve,ms));
const emit=(socket,event,payload={})=>new Promise((resolve)=>socket.emit(event,payload,resolve));
function once(socket,event,predicate=()=>true,timeout=4000){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{socket.off(event,handler);reject(new Error(`${event} zaman aşımı`));},timeout);function handler(value){if(!predicate(value))return;clearTimeout(timer);socket.off(event,handler);resolve(value);}socket.on(event,handler);});}
async function connect(){const socket=io(`http://127.0.0.1:${port}`,{transports:["websocket"]});await once(socket,"connect");return socket;}
async function health(){return new Promise((resolve,reject)=>http.get(`http://127.0.0.1:${port}/health`,(response)=>{let body="";response.on("data",(chunk)=>body+=chunk);response.on("end",()=>resolve(JSON.parse(body)));}).on("error",reject));}
function validState(state,count){return state.players.length===count&&state.players.every((player)=>Number.isFinite(player.x)&&Number.isFinite(player.y)&&[0,1].includes(player.team)&&player.energy>=0&&player.energy<=100)&&Number.isFinite(state.ball.x)&&Number.isFinite(state.ball.y)&&Number.isFinite(state.ball.vx)&&Number.isFinite(state.ball.vy)&&state.score.length===2;}

(async()=>{
  await new Promise((resolve,reject)=>{server.stdout.on("data",(data)=>data.toString().includes("hazır")&&resolve());server.once("exit",(code)=>reject(new Error(`server ${code}`)));});
  assert.deepEqual(await health(),{ok:true,game:"campus-head-ball",engine:"5.7.0"});
  const clientSource=fs.readFileSync(path.join(__dirname,"../public/client.js"),"utf8"),stylesSource=fs.readFileSync(path.join(__dirname,"../public/styles.css"),"utf8"),upgradeSource=fs.readFileSync(path.join(__dirname,"../public/upgrade.css"),"utf8"),musicPath=path.join(__dirname,"../public/assets/stadium-theme.mp3"),fighterPaths=Array.from({length:17},(_,index)=>path.join(__dirname,`../public/assets/fighter-${index+1}.png`));
  const newStagePaths=[15,16,17,18].map((number)=>path.join(__dirname,`../public/assets/stage-${number}.png`));
  assert(clientSource.includes('new Audio("/assets/stadium-theme.mp3")'));
  assert(!clientSource.includes("voiceLab")&&!clientSource.includes("voiceGenerate"));
  assert(!fs.readFileSync(path.join(__dirname,"../server.js"),"utf8").includes("/api/voice/"));
  assert(clientSource.includes("const MATCH_MUSIC_LEVEL=10"));
  assert(clientSource.includes("setMusicLevel(MATCH_MUSIC_LEVEL);ensureAudio();playIntro()"));
  assert(clientSource.includes('$("musicVolume").oninput=(event)=>setMusicLevel(event.target.value)'));
  assert(!clientSource.includes("scheduleMusic"));
  assert(fs.statSync(musicPath).size>2000000);
  assert(fighterPaths.every((fighterPath)=>fs.statSync(fighterPath).size>500000));
  assert(newStagePaths.every((stagePath)=>fs.statSync(stagePath).size>1000000));
  assert(clientSource.includes("Öğrenci Merkezi -1")&&clientSource.includes("Suna Kıraç Kütüphanesi İç Avlu")&&clientSource.includes("Mühendislik Merdivenleri")&&clientSource.includes("Şadırvan Salonu")&&clientSource.includes("Gün Batımı")&&clientSource.includes("Gündüz")&&clientSource.includes("Gece")&&clientSource.includes("stage-period-tabs")&&clientSource.includes("stage-period-grid"));
  assert(stylesSource.includes("#audioControls{position:fixed;z-index:30;right:14px;bottom:12px"));
  assert(upgradeSource.includes(".game-quit{position:absolute;z-index:8;bottom:12px"));
  assert(upgradeSource.includes("@media(min-width:1301px){.game-footer-hud{left:250px;right:360px;width:auto"));
  assert(upgradeSource.includes("@media(min-width:901px) and (max-width:1300px){.game-footer-hud{left:190px;right:16px;bottom:60px"));
  assert.deepEqual(engine.ARENA_WIDTHS,{compact:1376,wide:1720});
  assert.equal(engine.STAGE_COUNT,54);
  assert.equal(engine.ROSTER.length,17);
  assert.deepEqual(engine.ROSTER.map((fighter)=>fighter.name),["Alpsu","Alto","Caner","Eaytaclar","Eco","Irene","İdiko","İhsan","Jibiji","Kaynımol","Küçük Durak","Littlerose","Nevşo","Teker","UCY","Ulushain","Ysoner"]);
  assert.equal(engine.BALLS.length,1);
  assert.equal(engine.BALLS[0].name,"Hafif Köpük");
  assert.deepEqual(engine.AI_DIFFICULTIES,["easy","normal","hard"]);
  assert(engine.BALLS[0].bounce>.88&&engine.BALLS[0].bounce<.94);
  assert.equal(engine.goalTopFor({arenaSize:"compact"}),350);
  assert.equal(engine.goalTopFor({arenaSize:"wide"}),325);
  assert.equal(engine.goalTopFor({arenaSize:"compact",format:"1v1"}),336);
  assert.equal(engine.goalTopFor({arenaSize:"wide",format:"1v1"}),311);
  assert.deepEqual(engine.activeSlots({format:"1v1"}),[0,2]);
  assert.deepEqual(engine.activeSlots({format:"2v2"}),[0,1,2,3]);
  assert.equal(engine.HITBOX.headY,-190);assert.equal(engine.HITBOX.bodyY,-57);assert.equal(engine.HITBOX.activeHeadRadius,48);
  assert(engine.ROSTER.every((fighter)=>fighter.stories.length>=3));
  assert.equal(engine.ROSTER[4].special,"Işık Kafa");assert.equal(engine.ROSTER[8].special,"Mıknatıs Kafa");assert.equal(engine.ROSTER[14].special,"Ayna Kafa");assert.equal(engine.ROSTER[1].special,"Geometri Kafa");assert.equal(engine.ROSTER[6].special,"Lodos Kafa");
  const gameHtml=require("fs").readFileSync(path.join(__dirname,"../public/index.html"),"utf8"),upgradeCss=require("fs").readFileSync(path.join(__dirname,"../public/upgrade.css"),"utf8"),clientJs=require("fs").readFileSync(path.join(__dirname,"../public/client.js"),"utf8");assert(gameHtml.includes('class="game-footer-hud"'));assert(gameHtml.includes('id="quitMatch"')&&gameHtml.includes('id="quitLobby"')&&gameHtml.includes('id="leagueOverlay"'));assert(gameHtml.includes('id="careerSetupOverlay"')&&gameHtml.includes('id="resetSeasonBtn"')&&gameHtml.includes('id="resetCupBtn"'));assert(gameHtml.includes("EĞİL / HIZLI İN"));assert(gameHtml.includes('/assets/fighter-9.png')&&gameHtml.includes('/assets/fighter-16.png'));assert(upgradeCss.includes(".game-screen.active{position:fixed"));assert(upgradeCss.includes("height:100vh;height:100dvh"));assert(upgradeCss.includes("grid-template-columns:minmax(0,1fr) auto"));assert(upgradeCss.includes(".career-setup-sheet")&&upgradeCss.includes(".cpu-slot select"));assert(clientJs.includes("selectCpuCharacter")&&clientJs.includes("leagueSchedule(career.config.teamCount,career.config.legs)")&&clientJs.includes('new Audio("/assets/stadium-theme.mp3")')&&clientJs.includes("window.confirm")&&clientJs.includes("EĞİLEREK BLOK")&&clientJs.includes('precision:"GEOMETRİ KAFA"')&&clientJs.includes('lodos:"LODOS KAFA"'));
  const careerContext={Math,result:null},careerCore=clientJs.slice(clientJs.indexOf("const LEAGUE_CLUBS="),clientJs.indexOf("function loadCareer"));vm.runInNewContext(`${careerCore};result={leagueSchedule,newCareer,leagueMatchCount};`,careerContext);assert.equal(careerContext.result.leagueSchedule(4,1).length,3);assert.equal(careerContext.result.leagueSchedule(6,2).length,10);assert.equal(careerContext.result.leagueSchedule(8,2).length,14);assert(careerContext.result.leagueSchedule(8,2).every((round)=>round.length===4));const configuredLeague=careerContext.result.newCareer("season",{teamCount:6,legs:2,difficulty:"hard"}),configuredCup=careerContext.result.newCareer("cup",{rounds:4,difficulty:"easy"});assert.equal(configuredLeague.table.length,6);assert.equal(careerContext.result.leagueMatchCount(configuredLeague),10);assert.deepEqual(JSON.parse(JSON.stringify(configuredCup.config)),{rounds:4,difficulty:"easy"});

  const kickoffRoom={worldWidth:1720,arenaSize:"wide",lastKickoffSide:0,kickoffStreak:0},kickoffs=[];
  for(let i=0;i<80;i++)kickoffs.push(engine.nextKickoffX(kickoffRoom));
  assert(kickoffs.every((x)=>Math.abs(x-860)>=70&&Math.abs(x-860)<=180));
  assert(kickoffs.some((x)=>x<860)&&kickoffs.some((x)=>x>860));

  const goalRoom={code:"TEST",phase:"playing",worldWidth:1376,rules:{duration:90,goalLimit:5},score:[0,0],ball:engine.createBall(0),players:[],winner:null,pause:0,shake:0};goalRoom.ball.x=engine.LEFT_LINE-12;goalRoom.ball.y=570;goalRoom.ball.vx=-100;engine.updateBall(goalRoom);assert.equal(goalRoom.phase,"goalPause");assert.deepEqual(goalRoom.score,[0,1]);
  const wideGoalRoom={...goalRoom,phase:"playing",format:"2v2",arenaSize:"wide",worldWidth:1720,score:[0,0],winner:null,ball:engine.createBall(0)};wideGoalRoom.ball.x=1720-engine.LEFT_LINE+12;wideGoalRoom.ball.y=340;wideGoalRoom.ball.vx=100;engine.updateBall(wideGoalRoom);assert.deepEqual(wideGoalRoom.score,[1,0]);
  const compactCrossbarRoom={...goalRoom,phase:"playing",format:"2v2",arenaSize:"compact",worldWidth:1376,score:[0,0],winner:null,ball:engine.createBall(0)};compactCrossbarRoom.ball.x=1376-engine.LEFT_LINE+12;compactCrossbarRoom.ball.y=340;compactCrossbarRoom.ball.vx=100;engine.updateBall(compactCrossbarRoom);assert.deepEqual(compactCrossbarRoom.score,[0,0]);assert.equal(compactCrossbarRoom.phase,"playing");

  const blueDefender=engine.createPlayer(0,0,1720),blueStriker=engine.createPlayer(1,1,1720),redDefender=engine.createPlayer(2,2,1720),redStriker=engine.createPlayer(3,3,1720);
  assert.deepEqual([blueDefender.team,blueStriker.team,redDefender.team,redStriker.team],[0,0,1,1]);
  assert(blueDefender.x<blueStriker.x&&redDefender.x>redStriker.x);
  const camper=engine.createPlayer(0,0,1376);camper.x=engine.PLAYER_LEFT;for(let tick=0;tick<300;tick++)engine.updatePlayer({code:"TEST",worldWidth:1376},camper,{left:true});assert(camper.x>=engine.PLAYER_LEFT+70);assert(camper.goalCamp>2.45);
  const strictCamper=engine.createPlayer(0,0,1720),strictRoom={code:"STRICT",format:"2v2",arenaSize:"wide",worldWidth:1720};strictCamper.x=engine.PLAYER_LEFT;for(let tick=0;tick<105;tick++)engine.updatePlayer(strictRoom,strictCamper,{left:true});assert(strictCamper.goalLock>4);assert(strictCamper.x>=engine.PLAYER_LEFT+150);for(let tick=0;tick<120;tick++)engine.updatePlayer(strictRoom,strictCamper,{left:true});assert(strictCamper.x>=engine.PLAYER_LEFT+150);strictCamper.x=600;for(let tick=0;tick<310;tick++)engine.updatePlayer(strictRoom,strictCamper,{});assert.equal(strictCamper.goalLock,0);for(let tick=0;tick<70;tick++)engine.updatePlayer(strictRoom,strictCamper,{left:true});assert(strictCamper.x<engine.PLAYER_LEFT+150);assert.equal(strictCamper.goalLock,0);
  const duelCamper=engine.createPlayer(0,0,1376),duelRoom={code:"DUEL",format:"1v1",arenaSize:"compact",worldWidth:1376};duelCamper.x=engine.PLAYER_LEFT;for(let tick=0;tick<130;tick++)engine.updatePlayer(duelRoom,duelCamper,{left:true});assert(duelCamper.goalLock>4);assert(duelCamper.x>=engine.PLAYER_LEFT+110);for(let tick=0;tick<170;tick++)engine.updatePlayer(duelRoom,duelCamper,{left:true});assert(duelCamper.x>=engine.PLAYER_LEFT+110);duelCamper.x=560;for(let tick=0;tick<300;tick++)engine.updatePlayer(duelRoom,duelCamper,{});assert.equal(duelCamper.goalLock,0);

  const croucher=engine.createPlayer(0,0,1376);croucher.vx=210;engine.updatePlayer({code:"CROUCH",format:"1v1",arenaSize:"compact",worldWidth:1376},croucher,{down:true,right:true});assert(croucher.crouching);assert.equal(croucher.action,"crouch");assert(croucher.vx<210);assert(engine.CROUCH_HITBOX.headY>engine.HITBOX.headY);
  const crouchBall=engine.createBall(0),crouchGuard=engine.createPlayer(0,0,1376),crouchRoom={code:"BLOCK",worldWidth:1376,ball:crouchBall};crouchGuard.x=300;crouchGuard.crouching=true;crouchBall.x=crouchGuard.x+58;crouchBall.y=crouchGuard.y+engine.CROUCH_HITBOX.bodyY;crouchBall.vx=-460;crouchBall.vy=30;assert(engine.collideBallCircle(crouchRoom,crouchGuard,crouchGuard.x,crouchGuard.y+engine.CROUCH_HITBOX.bodyY,engine.CROUCH_HITBOX.bodyRadius,false));assert(crouchBall.vx>260);assert(crouchBall.vy< -300);assert.equal(crouchBall.lastTouchKind,"crouchBlock");
  const aiDuel=engine.createPlayer(2,0,1376),aiDuelRoom={code:"AI1",phase:"playing",kickoff:0,format:"1v1",arenaSize:"compact",worldWidth:1376,ball:engine.createBall(0)};aiDuel.x=1020;aiDuelRoom.ball.x=350;aiDuelRoom.ball.y=390;aiDuelRoom.ball.vx=-80;assert(engine.aiInput(aiDuelRoom,aiDuel).left,"1v1 CPU rakip yarı sahaya ilerlemeli");for(let tick=0;tick<150;tick++)engine.updatePlayer(aiDuelRoom,aiDuel,engine.aiInput(aiDuelRoom,aiDuel));assert(aiDuel.x<688,"1v1 CPU fiziksel olarak orta saha çizgisini geçmeli");
  const aiSupport=engine.createPlayer(2,0,1376),aiTeamRoom={code:"AI2",phase:"playing",kickoff:0,format:"2v2",arenaSize:"compact",worldWidth:1376,ball:engine.createBall(0)};aiSupport.x=1220;aiTeamRoom.ball.x=300;aiTeamRoom.ball.y=350;assert(engine.aiInput(aiTeamRoom,aiSupport).left,"2v2 savunmacı orta saha destek çizgisine çıkmalı");for(let tick=0;tick<120;tick++)engine.updatePlayer(aiTeamRoom,aiSupport,engine.aiInput(aiTeamRoom,aiSupport));assert(aiSupport.x<950,"2v2 savunmacı geride donmak yerine desteğe çıkmalı");
  const aiGuard=engine.createPlayer(0,0,1376),aiGuardRoom={code:"AI3",phase:"playing",kickoff:0,format:"1v1",worldWidth:1376,ball:engine.createBall(0)};aiGuard.x=310;aiGuardRoom.ball.x=255;aiGuardRoom.ball.y=555;aiGuardRoom.ball.vx=-220;const guardInput=engine.aiInput(aiGuardRoom,aiGuard);assert(guardInput.down&&!guardInput.jump,"CPU alçak kendi-kale tehdidinde eğilerek blok yapmalı");
  const easyAi=engine.createPlayer(2,0,1376),hardAi=engine.createPlayer(2,0,1376),difficultyBall=engine.createBall(0);difficultyBall.x=350;difficultyBall.y=390;easyAi.aiCooldown=hardAi.aiCooldown=0;const easyInput=engine.aiInput({code:"EASY",phase:"playing",kickoff:0,format:"1v1",worldWidth:1376,cpuDifficulty:"easy",ball:difficultyBall},easyAi),hardInput=engine.aiInput({code:"HARD",phase:"playing",kickoff:0,format:"1v1",worldWidth:1376,cpuDifficulty:"hard",ball:difficultyBall},hardAi);assert.equal(easyInput.cpuScale,.86);assert.equal(hardInput.cpuScale,1);assert(hardAi.aiCooldown<easyAi.aiCooldown);

  const standingHeader=engine.createPlayer(0,0),standingRoom={code:"HEAD",ball:engine.createBall(0)};standingRoom.ball.x=standingHeader.x+60;standingRoom.ball.y=standingHeader.y+engine.HITBOX.headY;standingRoom.ball.vx=-300;assert(engine.collideBallCircle(standingRoom,standingHeader,standingHeader.x,standingHeader.y+engine.HITBOX.headY,engine.HITBOX.headRadius,true));assert.equal(standingRoom.ball.lastTouchKind,"head");
  const dribbler=engine.createPlayer(0,0),dribbleRoom={code:"DRIBBLE",ball:engine.createBall(0)};dribbler.vx=300;dribbleRoom.ball.x=dribbler.x+60;dribbleRoom.ball.y=610-dribbleRoom.ball.radius;dribbleRoom.ball.vx=0;dribbleRoom.ball.vy=0;engine.collideBallCircle(dribbleRoom,dribbler,dribbler.x,dribbler.y+engine.HITBOX.bodyY,engine.HITBOX.bodyRadius,false);assert.equal(dribbleRoom.ball.lastTouchKind,"toePop");assert(-dribbleRoom.ball.vy>600);
  {const ball=engine.createBall(0),room={code:"ROLL",phase:"playing",worldWidth:1720,rules:{duration:90,goalLimit:99},score:[0,0],winner:null,pause:0,players:[],ball};ball.x=300;ball.y=610-ball.radius;ball.vx=700;ball.vy=0;let minimumY=ball.y,groundFrames=0;for(let tick=0;tick<180;tick++){engine.updateBall(room);minimumY=Math.min(minimumY,ball.y);if(ball.y>610-ball.radius-20)groundFrames++;}assert(minimumY<610-ball.radius-70);assert(groundFrames/180<.25);}
  const pinBall=engine.createBall(0),pinLeft=engine.createPlayer(0,0),pinRight=engine.createPlayer(2,1),pinRoom={code:"PIN",worldWidth:1720,players:[pinLeft,pinRight],ball:pinBall};pinLeft.x=805;pinRight.x=915;pinBall.x=860;pinBall.y=565;pinBall.vx=0;pinBall.vy=0;for(let tick=0;tick<30;tick++)engine.resolveBallPin(pinRoom);const firstReleaseSpeed=Math.hypot(pinBall.vx,pinBall.vy);assert.equal(pinBall.pinBurstCount,1);assert(firstReleaseSpeed>700);pinBall.pinCooldown=0;pinBall.pinTimer=0;pinBall.x=860;pinBall.y=565;pinBall.vx=0;pinBall.vy=0;for(let tick=0;tick<30;tick++)engine.resolveBallPin(pinRoom);const repeatReleaseSpeed=Math.hypot(pinBall.vx,pinBall.vy);assert.equal(pinBall.pinBurstCount,2);assert(repeatReleaseSpeed>firstReleaseSpeed+150);assert(pinBall.vy< -750);
  const scrumBall=engine.createBall(0),blueA=engine.createPlayer(0,0),blueB=engine.createPlayer(1,1),redSolo=engine.createPlayer(2,2),scrumRoom={code:"SCRUM",worldWidth:1720,players:[blueA,blueB,redSolo],ball:scrumBall};blueA.x=760;blueB.x=820;redSolo.x=900;scrumBall.x=860;scrumBall.y=565;scrumBall.vx=scrumBall.vy=0;blueA.moveIntent=1;blueB.moveIntent=-1;redSolo.moveIntent=-1;const redStart=redSolo.x;for(let tick=0;tick<40;tick++)engine.resolveTeamScrum(scrumRoom);assert.equal(scrumBall.vx,480);assert.equal(scrumBall.vy,-520);assert(redSolo.x>redStart);assert.equal(redSolo.vx,260);assert(scrumBall.scrumCooldown>1);
  const passiveBall=engine.createBall(0),passiveA=engine.createPlayer(0,0),passiveB=engine.createPlayer(1,1),passiveRed=engine.createPlayer(2,2),passiveRoom={code:"PASSIVE",worldWidth:1720,players:[passiveA,passiveB,passiveRed],ball:passiveBall};passiveA.x=760;passiveB.x=820;passiveRed.x=900;passiveBall.x=860;passiveBall.y=565;passiveBall.vx=passiveBall.vy=0;passiveA.moveIntent=passiveB.moveIntent=0;for(let tick=0;tick<60;tick++)engine.resolveTeamScrum(passiveRoom);assert.equal(passiveBall.vx,0);assert.equal(passiveRed.x,900);
  const stallBall=engine.createBall(0),stallLeft=engine.createPlayer(0,0),stallRight=engine.createPlayer(2,1),stallRoom={code:"STALL",worldWidth:1720,players:[stallLeft,stallRight],ball:stallBall};stallLeft.x=805;stallRight.x=915;stallBall.x=860;stallBall.y=565;stallBall.vx=stallBall.vy=0;let stallCleared=false,stallFrames=0;while(!stallCleared&&stallFrames<300){stallCleared=engine.resolveCrowdStall(stallRoom);stallFrames++;}assert(stallCleared);assert(stallFrames>=228&&stallFrames<=230);assert.equal(Math.abs(stallBall.vx),650);assert.equal(stallBall.vy,-790);assert(stallBall.stallCooldown>2);assert(stallBall.unpinGrace>=.38);
  const lowLoopBall=engine.createBall(0),lowLoopRoom={code:"LOW",worldWidth:1720,players:[],ball:lowLoopBall};lowLoopBall.x=860;lowLoopBall.y=573;lowLoopBall.vx=260;lowLoopBall.vy=0;let lowLifted=false,lowFrames=0;while(!lowLifted&&lowFrames<350){lowLifted=engine.resolveLowPlayLoop(lowLoopRoom);lowFrames++;}assert(lowLifted);assert(lowFrames>=330&&lowFrames<=332);assert.equal(lowLoopBall.vy,-720);assert(lowLoopBall.lowPlayCooldown>3);lowLoopBall.lowPlayCooldown=0;lowLoopBall.lowPlayTimer=4;lowLoopBall.y=400;assert.equal(engine.resolveLowPlayLoop(lowLoopRoom),false);assert.equal(lowLoopBall.lowPlayTimer,0);
  const shelfBall=engine.createBall(0),shelfDefender=engine.createPlayer(0,0,1720),shelfAttacker=engine.createPlayer(2,1,1720),shelfRoom={format:"2v2",arenaSize:"wide",worldWidth:1720,ball:shelfBall};shelfBall.x=160;shelfBall.y=340;shelfBall.vx=-420;assert(engine.isTopShelfShot(shelfRoom,shelfDefender));assert(!engine.isTopShelfShot(shelfRoom,shelfAttacker));shelfBall.y=380;assert(!engine.isTopShelfShot(shelfRoom,shelfDefender));

  const magnetPlayer=engine.createPlayer(0,engine.ROSTER.findIndex((fighter)=>fighter.name==="Jibiji")),magnetRoom={ball:engine.createBall(0)};magnetRoom.ball.x=magnetPlayer.x+250;magnetRoom.ball.y=magnetPlayer.y-80;const beforeMagnet=Math.hypot(magnetRoom.ball.x-(magnetPlayer.x+50),magnetRoom.ball.y-(magnetPlayer.y+engine.HITBOX.headY));for(let i=0;i<8;i++)engine.magnetBall(magnetRoom,magnetPlayer);magnetRoom.ball.x+=magnetRoom.ball.vx/60;magnetRoom.ball.y+=magnetRoom.ball.vy/60;const afterMagnet=Math.hypot(magnetRoom.ball.x-(magnetPlayer.x+50),magnetRoom.ball.y-(magnetPlayer.y+engine.HITBOX.headY));assert(afterMagnet<beforeMagnet);

  const precisionPlayer=engine.createPlayer(0,engine.ROSTER.findIndex((fighter)=>fighter.name==="Alto"),1720),precisionBall=engine.createBall(0),precisionRoom={code:"PRECISION",phase:"playing",kickoff:0,format:"2v2",arenaSize:"wide",worldWidth:1720,ball:precisionBall,players:[precisionPlayer]};precisionPlayer.energy=100;assert(engine.startAction(precisionRoom,precisionPlayer,"special"));assert.equal(precisionPlayer.specialKind,"precision");assert.equal(precisionPlayer.energy,50);precisionPlayer.actionClock=.3;precisionBall.x=precisionPlayer.x+31+60;precisionBall.y=precisionPlayer.y+engine.HITBOX.headY;precisionBall.vx=-180;precisionBall.vy=0;assert(engine.collideBallCircle(precisionRoom,precisionPlayer,precisionPlayer.x+31,precisionPlayer.y+engine.HITBOX.headY,engine.HITBOX.activeHeadRadius,true));assert.equal(precisionBall.lastTouchKind,"precision");assert(precisionBall.vx>500);assert(precisionBall.vy< -180);assert.equal(precisionBall.spin,0);
  const lodosPlayer=engine.createPlayer(0,engine.ROSTER.findIndex((fighter)=>fighter.name==="İdiko"),1720),lodosBall=engine.createBall(0),lodosRoom={code:"LODOS",phase:"playing",kickoff:0,format:"2v2",arenaSize:"wide",worldWidth:1720,ball:lodosBall,players:[lodosPlayer]};lodosPlayer.energy=100;assert(engine.startAction(lodosRoom,lodosPlayer,"special"));assert.equal(lodosPlayer.specialKind,"lodos");assert.equal(lodosPlayer.energy,50);lodosPlayer.actionClock=.3;lodosBall.x=lodosPlayer.x+31+60;lodosBall.y=lodosPlayer.y+engine.HITBOX.headY;lodosBall.vx=-180;lodosBall.vy=0;assert(engine.collideBallCircle(lodosRoom,lodosPlayer,lodosPlayer.x+31,lodosPlayer.y+engine.HITBOX.headY,engine.HITBOX.activeHeadRadius,true));assert.equal(lodosBall.lastTouchKind,"lodos");assert.equal(lodosBall.floatTimer,.72);assert(lodosBall.vy< -550);const lodosVy=lodosBall.vy;lodosRoom.players=[];lodosRoom.rules={duration:90,goalLimit:99};lodosRoom.score=[0,0];lodosRoom.winner=null;lodosRoom.pause=0;engine.updateBall(lodosRoom);assert(lodosBall.floatTimer<.72&&lodosBall.floatTimer>.69);assert(lodosBall.vy-lodosVy<12);

  const soloMode=await connect(),soloCreated=await emit(soloMode,"createSolo",{name:"Lig Oyuncusu",competition:"season",rules:{duration:180,goalLimit:7},character:5,difficulty:"hard"});assert(soloCreated.ok);assert.equal(soloCreated.room.playMode,"single");assert.equal(soloCreated.room.competition,"season");assert.equal(soloCreated.room.cpuDifficulty,"hard");assert.equal(soloCreated.room.format,"1v1");assert.equal(soloCreated.room.arenaSize,"compact");assert.deepEqual(soloCreated.room.rules,{duration:180,goalLimit:7});assert.equal(soloCreated.room.selections[0],5);assert.equal(soloCreated.room.goalTop,336);const blocked=await connect();assert.equal((await emit(blocked,"joinRoom",{name:"Davetsiz",code:soloCreated.room.code})).ok,false);blocked.disconnect();const soloTwoLobby=once(soloMode,"lobby",(next)=>next.format==="2v2");assert((await emit(soloMode,"setFormat",{format:"2v2"})).ok);assert.equal((await soloTwoLobby).goalTop,350);assert.equal((await emit(soloMode,"selectCpuCharacter",{slot:1,index:5})).ok,false);for(const [slot,index] of [[1,8],[2,9],[3,10]])assert((await emit(soloMode,"selectCpuCharacter",{slot,index})).ok);assert((await emit(soloMode,"setReady",{ready:true})).ok);const soloTwoStarted=once(soloMode,"matchStarted");assert((await emit(soloMode,"startMatch")).ok);const soloTwoState=await soloTwoStarted;assert(validState(soloTwoState,4));assert.equal(soloTwoState.format,"2v2");assert.equal(soloTwoState.cpuDifficulty,"hard");assert.equal(soloTwoState.players.filter((player)=>player.human).length,1);assert.equal(soloTwoState.players.filter((player)=>!player.human).length,3);assert.deepEqual(soloTwoState.players.map((player)=>player.character),[5,8,9,10]);assert.deepEqual(soloTwoState.players.map((player)=>player.team),[0,0,1,1]);assert((await emit(soloMode,"leaveRoom")).ok);soloMode.disconnect();
  const quickA=await connect(),quickB=await connect(),quickWaiting=await emit(quickA,"quickMatch",{name:"Hızlı A"});assert(quickWaiting.ok&&quickWaiting.waiting);const quickLobby=once(quickA,"lobby",(next)=>next.format==="2v2");assert((await emit(quickA,"setFormat",{format:"2v2"})).ok);assert.equal((await quickLobby).format,"2v2");const quickMatched=await emit(quickB,"quickMatch",{name:"Hızlı B"});assert(quickMatched.ok&&quickMatched.matched);assert.equal(quickMatched.room.code,quickWaiting.room.code);assert.equal(quickMatched.room.members.length,2);assert.equal(quickMatched.room.format,"2v2");quickA.disconnect();quickB.disconnect();
  const ownerA=await connect(),ownerB=await connect(),owned=await emit(ownerA,"createRoom",{name:"Eski Sahip"});assert((await emit(ownerB,"joinRoom",{name:"Yeni Sahip",code:owned.room.code})).ok);const ownerChanged=once(ownerB,"lobby",(next)=>next.hostId===ownerB.id);assert((await emit(ownerA,"leaveRoom")).ok);assert.equal((await ownerChanged).hostId,ownerB.id);ownerA.disconnect();ownerB.disconnect();

  const host=await connect(),guestA=await connect(),guestB=await connect(),guestC=await connect();
  const made=await emit(host,"createRoom",{name:"Kurucu"});assert(made.ok&&made.sessionToken);assert.equal(made.room.format,"2v2");assert.equal(made.room.arenaSize,"wide");assert.equal(made.room.goalTop,325);
  const joinedA=await emit(guestA,"joinRoom",{name:"Kırmızı 1",code:made.room.code}),joinedB=await emit(guestB,"joinRoom",{name:"Mavi 2",code:made.room.code}),joinedC=await emit(guestC,"joinRoom",{name:"Kırmızı 2",code:made.room.code});assert(joinedA.ok&&joinedB.ok&&joinedC.ok);
  await wait(80);assert.equal((await emit(host,"setFormat",{format:"1v1"})).ok,false);
  assert((await emit(host,"setArenaSize",{arenaSize:"compact"})).ok);
  host.emit("selectStage",{index:13});await wait(50);
  for(const [socket,index] of [[host,0],[guestA,1],[guestB,2],[guestC,3]]){assert((await emit(socket,"selectCharacter",{index})).ok);assert((await emit(socket,"setReady",{ready:true})).ok);}
  const started=once(host,"matchStarted");assert((await emit(host,"startMatch")).ok);const opening=await started;assert(validState(opening,4));assert.equal(opening.format,"2v2");assert.equal(opening.arenaSize,"compact");assert.equal(opening.worldWidth,1376);assert.equal(opening.goalTop,350);assert.equal(opening.stage,13);assert.equal(opening.ballType,0);assert(opening.players.every((player)=>player.human));assert.equal(new Set(opening.players.map((player)=>player.character)).size,4);
  for(const socket of [host,guestA,guestB,guestC])socket.emit("skipIntro");await once(host,"introEnded");const live=await once(host,"state",(next)=>next.phase==="playing"&&next.kickoff===0);assert(validState(live,4));
  guestC.disconnect();await wait(100);const cpuTakeover=await once(host,"state",(next)=>next.players.some((player)=>player.side===3&&!player.human));assert(validState(cpuTakeover,4));
  const returning=await connect(),resumed=await emit(returning,"resumeSession",{code:made.room.code,token:joinedC.sessionToken});assert(resumed.ok&&resumed.state);assert(resumed.state.players.find((player)=>player.side===3).human);returning.disconnect();guestA.disconnect();guestB.disconnect();host.disconnect();

  const solo=await connect();const soloRoom=await emit(solo,"createRoom",{name:"Tek Oyuncu"});assert((await emit(solo,"setFormat",{format:"1v1"})).ok);assert((await emit(solo,"setArenaSize",{arenaSize:"wide"})).ok);assert((await emit(solo,"selectCharacter",{index:3})).ok);assert((await emit(solo,"setReady",{ready:true})).ok);const soloStarted=once(solo,"matchStarted");assert((await emit(solo,"startMatch")).ok);const soloState=await soloStarted;assert(validState(soloState,2));assert.equal(soloState.format,"1v1");assert.equal(soloState.arenaSize,"wide");assert.equal(soloState.worldWidth,1720);assert.equal(soloState.players.filter((player)=>player.human).length,1);assert.equal(soloState.players.filter((player)=>!player.human).length,1);assert.deepEqual(soloState.players.map((player)=>player.team),[0,1]);solo.disconnect();

  console.log("✓ 1'e 1 / 2'ye 2 maç düzeni ve bağımsız kompakt / geniş saha seçimi çalışıyor");
  console.log("✓ dört eşzamanlı oyuncu, takım koltukları, on altı benzersiz karakter ve seçilebilir CPU kadrosu doğrulandı");
  console.log("✓ bağlantı kopunca ilgili koltuğu CPU devralıyor, oyuncu aynı maça geri dönebiliyor");
  console.log("✓ kontrollü-rastgele sağ/sol başlama noktaları adil merkez bandında kalıyor");
  console.log("✓ geniş saha kalesi yükseltildi; 2'ye 2 kale yasağı hızlı, kişisel ve süreli çalışıyor");
  console.log("✓ 1'e 1 kalesi 14 piksel yükseldi; 2 saniyelik ihlal 110 piksel / 4,8 saniye kişisel yasak uyguluyor");
  console.log("✓ tekrarlayan sıkışma açık koridora daha güçlü kırılıyor; tek Hafif Köpük topu kararlı");
  console.log("✓ 2'ye 1 ikili baskıda sayısal üstünlük fiziksel olarak çalışıyor; tek takım arkadaşının baskısı yeterli");
  console.log("✓ bağımsız ilerleme denetçisi kalabalıkta 3,8 saniye ilerlemeyen topu açık koridora çıkarıyor");
  console.log("✓ 5,5 saniyelik alçak oyun denetçisi topu yeniden kafa yüksekliğine kaldırıyor");
  console.log("✓ karakter bilgisi ve kontroller tek yatay HUD satırında; oyun ekranı görünüm alanına sabit");
  console.log("✓ on sekiz arena hem kompakt hem geniş saha durumuyla sunucuda senkronize");
  console.log("✓ tek oyunculu hızlı maç/lig/kupa odaları ile çevrim içi hızlı eşleşme ayrıştırıldı");
  console.log("✓ tek oyunculu 2'ye 2 seçimi üç CPU ile başlıyor; 1'e 1 ve 2'ye 2 CPU'ları rakip yarı sahaya ilerliyor");
  console.log("✓ lig 4/6/8 takım ve tek/çift devreyle 3–14 maça; kupa 2/3/4 tura yapılandırılıyor");
  console.log("✓ lig/kupa sıfırlama kontrolleri ve rahat/dengeli/usta CPU profilleri paketlendi");
  console.log("✓ S ile yerde eğilme, alçak savunma hitbox'ı ve kendi kalene golü azaltan güvenli blok çalışıyor");
  console.log("✓ lig karakteri ve lig kuralları yeni kariyer odasına taşınıyor; çıkış sunucudaki koltuğu temizliyor");
  console.log("✓ oda sahibi çıkarsa sahiplik kalan oyuncuya geçiyor; seçilen MP3 ve alt köşe ses/çıkış kontrolleri paketlendi");
  console.log("✓ kısaltılmış karakter hitbox'ları, dar üst-köşe koridoru, kafa, yerden aşırma ve anti-kamp fiziği kararlı");
  server.kill();
})().catch((error)=>{console.error(error);server.kill();process.exit(1);});
